# Copyright 2012 Google Inc.  All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at: http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distrib-
# uted under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.  See the License for
# specific language governing permissions and limitations under the License.

application: crisislanding-hr
version: 1
runtime: python27
threadsafe: true
api_version: 1
libraries:
- name: django
  version: "1.3"
- name: PIL
  version: "latest"

# Enabling warmup requests gives us the option to configure idle instances,
# if we need to prepare for traffic spikes ahead of time.  For details, see:
# https://developers.google.com/appengine/docs/adminconsole/performancesettings
inbound_services:
- warmup

handlers:
# Administrative API request handler
- url: .*/remote_api
  script: google.appengine.ext.remote_api.handler.application
  login: admin

# Static file handlers
- url: /crisismap/.static
  static_dir: static

- url: /crisismap/.js/(.*).js
  static_files: js/compiled/\1.js
  upload: js/compiled/(.*).js

# User-facing request handlers
- url: (/crisismap)?/*
  script: index.app

- url: /crisismap/[\w.-]+\.\w+/.admin
  script: admin.app
  login: required

- url: /crisismap/[\w.-]+\.\w+/.catalog
  script: catalog.app
  login: required

- url: /crisismap(/[\w.-]+\.\w+)?/.create
  script: create.app
  login: required

- url: /crisismap(/[\w.-]+\.\w+)?/.delete
  script: delete.app
  login: required

- url: /crisismap(/[\w.-]+\.\w+)?/.maps
  script: maps.app
  login: required

- url: /crisismap(/[\w.-]+\.\w+)?(/.maps)?/[\w-]+
  script: maps.app

- url: /crisismap(/[\w.-]+\.\w+)?/.publish
  script: publish.app
  login: required

- url: /crisismap/.redirect/[\w.-]+
  script: redirect.app

- url: /crisismap/.wms/tiles/.*
  script: wmscache.tilecache_main.app

# XHR or JSONP request handlers
- url: /crisismap/.api/.*
  script: api.app

- url: /crisismap/.diff/[\w-]+
  script: diff.app

- url: /crisismap/.legend
  script: legend_item_extractor.app

- url: /crisismap/.jsonp
  script: jsonp.app

- url: /crisismap/.metadata
  script: metadata.app

- url: /crisismap/.share/[\w-]+
  script: share.app
  login: required

- url: /crisismap/.wms/query
  script: wmscache.wms_query.app

- url: /crisismap/.wms/configure
  script: wmscache.tileset_config.app

# Cron or taskqueue tasks
- url: /crisismap/.metadata_fetch
  script: metadata_fetch.app
  login: admin

- url: /crisismap/.wms/tileworker
  script: wmscache.tileworker.app

- url: /crisismap/.wms/tileworker_cleanup
  script: wmscache.tileworker.app

